# Generated by Django 2.2.7 on 2019-11-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricpro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='match_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
